from .employees.employee_list import employee_list
from .employees.employee_form import employee_form
from .employees.employee_form import employee_edit_form
from .departments.department_list import department_list
from .departments.department_form import department_form
from .home import home
from .auth.logout import logout_user
from .computers.list import *
from .training_program.training_program import *
from .computers.form import *
from .training_program.training_form import *
